### ISSUE TITLE
Instruction ADD executes with 7 MSBs different from 0

### ISSUE THREAD

**Issue by joao1996f** [ul-lar/Adept#6]
The correct format for ADD instruction is:

```
0000000 | rs2 | rs1 | 000 | rd |  0110011
```
The decoder isn't checking if the 7MSBs are valid for a R-type instruction and continues the execution of the code.

The instruction `add t1, a0, a1` generates `00b50333` in the .hex file and this is correct.
With `80b50333` the decoder should generate a trap.

**Comment by lfiolhais** [comment]
Closed as of 081726a053a8a1ae6ff998dcba1e7f648bab76ca
